In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('data/orders_export_1.csv')

data.head(5)

,Name,Email,Financial Status,Paid at,Fulfillment Status,Fulfilled at,Accepts Marketing,Currency,Subtotal,Shipping,...,Tax 5 Value,Phone,Receipt Number,Duties,Billing Province Name,Shipping Province Name,Payment ID,Payment Terms Name,Next Payment Due At,Payment References
0,#1282,NaN,paid,NaN,unfulfilled,NaN,no,AUD,212.0,0.0,...,NaN,NaN,NaN,NaN,New South Wales,New South Wales,NaN,NaN,NaN,NaN
1,#1281,NaN,paid,NaN,unfulfilled,NaN,no,AUD,212.0,0.0,...,NaN,NaN,NaN,NaN,New South Wales,New South Wales,NaN,NaN,NaN,NaN
2,#1280,NaN,paid,NaN,fulfilled,2025-05-13 13:37:30 +1000,no,AUD,106.0,0.0,...,NaN,NaN,NaN,NaN,Victoria,Victoria,NaN,NaN,NaN,NaN
3,#1279,NaN,paid,NaN,partial,NaN,no,AUD,318.0,0.0,...,NaN,NaN,NaN,NaN,Queensland,Queensland,NaN,NaN,NaN,NaN
4,#1278,NaN,paid,NaN,fulfilled,2025-05-12 12:38:22 +1000,no,AUD,318.0,0.0,...,NaN,NaN,NaN,NaN,New South Wales,New South Wales,NaN,NaN,NaN,NaN